Geocoding sample
Esri/arcgis-maps-sdk-unreal-engine-samples pull request #12
Opened 2022-08-04 15:32 UTC by arash-sh

**Sample**
Geocoding: Enter an address to get the geographic location of it. The pawn will be moved to that location and show a visual cue. 
Reverse geocoding: Shift+ left click on a location to see the address. The queries are made through the Geocoding service API.

**Summary**
Enter an address on the text field in the top and the camera will move to that location and show a pin on that point as well as the address returned by the API.  Ray casts will determine the elevation of the point.
Clicking on a location while holding the shift will make a query to get the address/description of that point. A visual cue shows the address. The scale of the visual cue is set based on the distance from the camera and the text will face the camera. 

**Tests**
Windows

**ArcGIS Maps SDK Version**
1.0.0

2022-08-08 18:23 UTC, Jade-JadeH commented on sample_project/Content/SampleViewer/Samples/Geocoding/readme.md
> +2. While holding shift, left-click on a location on the map to get the address (or description) of that location.
numbering

2022-08-08 18:58 UTC, arash-sh commented on sample_project/Content/SampleViewer/Samples/Geocoding/readme.md
> +4. This sample is only set up to work with mouse and keyboard.
I think in general we should have two separate sections. 1 for how to use the sample, and 1 for how to reproduce it/how it works. Similar to some other runtime samples (e.g., https://github.com/Esri/arcgis-runtime-samples-dotnet/tree/main/src/UWP/ArcGISRuntime.UWP.Viewer/Samples/Analysis/DistanceMeasurement)
But if we do that we should do it for all samples

2022-08-08 21:46 UTC, mrnelson6 requested changes

2022-08-08 21:46 UTC, mrnelson6 commented on sample_project/Source/sample_project/Geocoding/QueryLocation.h
> +	UPROPERTY(VisibleAnywhere, Category = "ArcGISMapsSDK|SampleDefaultPawn")
You should remove the category from this

2022-08-08 21:46 UTC, mrnelson6 commented on sample_project/Source/sample_project/Geocoding/Geocoder.cpp
> +	if (FJsonSerializer::Deserialize(Reader, JsonObj) &&
Just how you added logic in for the routing sample do you want to add a case to handle an error with either:
1. There is an invalid api key
2. The api key does not have geocoding permissions?

2022-08-08 21:57 UTC, Jade-JadeH commented
very nice. However, when there're multiple possible locations if user enters an incomplete address and hit enter, it takes user to one of them and you cannot select from dropdown to choose which one is the intended address. (see screenshots below). Can you make a dropdown with a sorted list of address? You don't need to have all addresses listed, you can return the first 5 from the sorted list. If this is too involved, perhaps you could prevent from showing results before matching user's entering with the address 

intended:
![image](https://user-images.githubusercontent.com/86364673/183521531-f029151b-cfe4-4875-b7a9-272c058add62.png)

Actual result returned: 
If entering: 112 West Hamilton:
![image](https://user-images.githubusercontent.com/86364673/183521352-bf61fb5a-5477-4adf-96d2-7879b62ea66c.png)
if entering: 112 West Hamilton, PA 
![image](https://user-images.githubusercontent.com/86364673/183521452-d9457fd0-0277-4330-9440-9590a3e00aa4.png)

2022-08-09 17:35 UTC, arash-sh commented
> Can you make a dropdown with a sorted list of address? You don't need to have all addresses listed, you can return the first 5 from the sorted list. If this is too involved, perhaps you could prevent from showing results before matching user's entering with the address

I looked into this, and with the way the server responds, showing the top 5 would not be a good solution I think. For your example of "112 west Hamilton", the server returned 35 possible candidates, none of which is in State College. So if we give the top 5 (or even all 35), it would not help the user.
The service also returns a score of each candidate, which can be pretty high. In this example the top 3 candidates have a score of 98.21%. The top 10 have a score higher than 97%. So if we want to prevent showing the results until the intended location is found, we can't really rely on the score because the wrong candidates can still have a high score (even 100% doesn't guarantee correct answer, because there can be multiple candidates with 100% and it is possible that none of the is what the user intended).
I think as an alternative, we can show a message like in this image. The message will be shown when there are more than one candidates (but I think that will be very often the case even if the address is very specific). 
What do you think?
![temp](https://user-images.githubusercontent.com/2331510/183721161-40cd3547-94da-4091-98e6-7d24a05be480.jpg)

2022-08-09 17:43 UTC, arash-sh commented on sample_project/Source/sample_project/Geocoding/Geocoder.cpp
> +	if (FJsonSerializer::Deserialize(Reader, JsonObj) &&
This will be included in the next push. The above errors are only relevant for the address search since the reverse geocoding doesn't require an API. 
The reverse geocoding would still show an error if the service sent an error message. The only error that I could force was when the lat/lon are invalid, but that will (hopefully) not happen in our use case

2022-08-09 20:26 UTC, mrnelson6 approved these changes
Nice PR @arash-sh ! Good to merge

2022-08-09 20:31 UTC, merged