Quality of Life: Feature layer Refactor and updates
Esri/arcgis-maps-sdk-unreal-engine-samples pull request #129
Opened 2024-12-19 23:55 UTC by mmgaw113

**Sample**

- Refactor the feature layer sample to clean up and reformat the code
- Remake the feature item in C++ for more consistent performance across the sample
- Write the Blueprint functions in bp_FeatureLayer in c++ in order to remove the Blueprint class (Note this deletion is why weather_wbp and BlueprintWeather_wbp have changed)
- Update UI to show properties of currently selected feature
- Add input to Feature Layer Query so users can select a feature
- Add visual Feedback via Highlight material to show the currently selected feature

**Checklist**

- [ ] PR title follows convention - `keyword: Short description of change` 
- [ ] PR targets the correct branch 
- [ ] New Blueprints follow Unreal Naming Convention 
- [ ] Self-review of changes
- [ ] There are no warnings related to changes
- [ ] A build was made and tested on all relevant platforms
- [ ] No unrelated changes have been made to any other code or project files
- [ ] No unnecessary includes or namespaces added
- [ ] Code follows plugin coding style
- [ ] New code and changed code has proper formatting 
- [ ] No unintentional formatting changes
- [ ] Commits have descriptive titles

**Blueprints**
Feature Layer WBP: https://blueprintue.com/blueprint/939quqzf/

**ArcGIS Maps SDK Version**

Maps SDK 1.7 w/UE 5.3

2024-12-20 19:37 UTC, Jade-JadeH commented
Good to see that bp was removed from this sample, this is one of the things I want to improve on our sample repo. I see surface placement is also used. Great. 

1. I didn't checkout out the unity PR, but thought we're going to make the pins not overlapping?

![image](https://github.com/user-attachments/assets/51286fd1-5bc8-484a-8fbc-0596886e546c)

2. It the feature 0-indexed or 1-indexed? because when I select feature 0-6 I'm expecting to see 7 features but seeing 6, I tried a couple of other numbers and see the same. 
![image](https://github.com/user-attachments/assets/985d3715-6e6d-4b7c-b071-e5d7eef99a45)

3. How do I see the properties of the currently selected feature? Is it in the UI or in the detail panel? 
![image](https://github.com/user-attachments/assets/45da3f4b-6e33-4517-89c8-91fb8f9ecba6)

2024-12-20 19:40 UTC, mmgaw113 commented
> 1. I didn't checkout out the unity PR, but thought we're going to make the pins not overlapping?

In order to make them not over lap whatsoever, the pin mesh scale would be so incredibly small it would be difficult to see without the camera being super close. With this specific data set (trees), they are clustered together which makes it hard to not have any overlapping. This is pretty similar to how the unity one looked.

2024-12-20 19:41 UTC, mmgaw113 commented
> 2\. It the feature 0-indexed or 1-indexed? because when I select feature 0-6 I'm expecting to see 7 features but seeing 6, I tried a couple of other numbers and see the same.

It might be triggering the wrong portion of the If Statement that runs a forloop for Last Value - 1, I will have to look into it. But you are right, you should see 7.

2024-12-20 19:42 UTC, mmgaw113 commented
> 3\. How do I see the properties of the currently selected feature? Is it in the UI or in the detail panel?

Shift + Click on a pin. The properties panel will only show up after you click on a pin and it will auto-hide the outfield drop down. Additionally, if you want to see the outfield drop-down while the properties panel is active, it will hide the properties panel.

2024-12-20 23:46 UTC, Jade-JadeH commented
> > 3. How do I see the properties of the currently selected feature? Is it in the UI or in the detail panel?
> 
> Shift + Click on a pin. The properties panel will only show up after you click on a pin and it will auto-hide the outfield drop down. Additionally, if you want to see the outfield drop-down while the properties panel is active, it will hide the properties panel.

Aw ok, I see. I can see that based on what outfield you select, it shows different kind of properties which works very well. Based on this I noticed: 

1. the dropdown menu appears to behave strangely 
![UnrealEditor_svwKK21Vm3](https://github.com/user-attachments/assets/be0e1dd8-cef6-4408-b9be-420de84b6924)

Other comments I have are: 
1. A typo on the instruction: data set ---> dataset; I also think we should remove "we apologize for the inconvenience". 
2. Can we zoom to a point? For example, click on one point on the outliner and zoom to that point.

2024-12-20 23:55 UTC, mmgaw113 commented
Unfortunately that is expected behavior :/ The issue I was running into is that if we want it to show up when the outfields drop down is up, it needs to be bound to opposite of the book value for that toggle.

I could probably check if "selected feature" != nullptr before toggling it.

2024-12-20 23:57 UTC, mmgaw113 commented
I don't think we can zoom to a point based on the inspector. That functionality only works when not in play mode and it's the same for both engines. It would be really complicated to write and we'd need to do it in the viewport which would take up a lot of space. I think it would be a nice to have but not super important for the sample. Maybe a toolkit idea?

2024-12-20 23:58 UTC, Jade-JadeH commented
> I don't think we can zoom to a point based on the inspector. That functionality only works when not in play mode and it's the same for both engines. It would be really complicated to write and we'd need to do it in the viewport which would take up a lot of space. I think it would be a nice to have but not super important for the sample. Maybe a toolkit idea?

I can agree on that, I encountered this issue when I'm doing samples too.

2024-12-23 22:53 UTC, ZackAllen requested changes

2024-12-23 22:53 UTC, ZackAllen commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.cpp
> +			item->Index = StartValue;
A lot of repeat code here with the block starting in 453. Any reason the for loop on line 437 doesn't cover this case?

2024-12-23 22:54 UTC, ZackAllen commented
Behavior of the sample worked correctly for me. Pins could use more adjustment, there is more overlapping here than the Unity implementation.

2024-12-24 05:06 UTC, avr757 commented
The UI look great overall, nice work!!  just a few suggestions:

1. The spacing between these menus seems inconsistent, we can improve this by moving the property info menu down a bit so that the spacing will be equal.
![image](https://github.com/user-attachments/assets/069ce932-1619-4feb-b3a2-ddac08e59995)

2. It seems in the "Point Layer" text the "L" is capitalized? I think we could also add a sentence to the instruction about clicking the pins using the "Shift + Click" so users will know about this new instruction.
![image](https://github.com/user-attachments/assets/8c0131b9-fe79-47b1-a7c6-e4f2a1557e4d)

3. I was a bit confused with this UX: I thought after we deselect/reselect some of the properties in the dropdown, the number of these properties will automatically updates. It turns out I have to click a different pin to see the updates? Is this intentional just out of curiosity? I just thought it would be an easier UX for the users if it automatically updates.
https://github.com/user-attachments/assets/3fdcc40b-abb0-4746-a72b-3fbb00d45a06

2025-01-06 17:09 UTC, mmgaw113 commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.cpp
> +			item->Index = StartValue;
Yes, there are 3 blocks because there are 3 possibilities for getting the features. The first of which being "Get all features". 
Second being get features from x to y (1-100 for instance) the third is specifically a fail safe. If the feature layer only has 100 feature but a user wants to get feature item 151, it will literally crash the engine with an array index out of bounds error. I am sure there is a way to simplify this code so it does not repeat as often however this is how it currently works. I will look into creating a function that takes in a min and max integer values in order and then run the 4 loops.

2025-01-06 17:11 UTC, mmgaw113 commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.cpp
> +			item->Index = StartValue;
There is also a case where start value = last value so it doesn't run a loop at all. Just gets the first value.

2025-01-06 17:53 UTC, mmgaw113 commented
> 3\. I was a bit confused with this UX: I thought after we deselect/reselect some of the properties in the dropdown, the number of these properties will automatically updates. It turns out I have to click a different pin to see the updates? Is this intentional just out of curiosity? I just thought it would be an easier UX for the users if it automatically updates.
>     Video: https://github.com/user-attachments/assets/3fdcc40b-abb0-4746-a72b-3fbb00d45a06

This is expected. The behavior is identical in Unity. There isn't an easy way to make it update after changing selected properties without running it every frame on a Tick/Update function.

2025-01-06 20:05 UTC, ZackAllen approved these changes

2025-01-07 16:15 UTC, merged