Flight simulator sample
Esri/arcgis-maps-sdk-unreal-engine-samples pull request #19
Opened 2022-08-17 11:01 UTC by PauFlorenti

**Sample**

Updating the Flight Simulator sample in its branch.

**Summary**
* Reimported ship mesh to fix orientation.
* Ship movement done through physics.
* Created a simple HUD showing where the ship is heading.
* Changed controls and added mouse control support for pitch and roll.
* Improved crash widget, allowing to quit the sample.
* Updated readme.md for Flight Simulator sample.

**ArcGIS Maps SDK Version**
1.0.0

2022-08-17 18:03 UTC, mrnelson6 commented
Ok a couple things of feedback. Overall looks good.
1. There is an API Key in your level. Can you remove that?
2. Can you make it so the ship has a higher top speed and a faster acceleration? I think it would be cooler if the pilot was able to cover larger distances. With that being said I noticed something weird when you went a distance from the start where the airplane disappeared do you know what is up with that?
3. We want the sub levels to be linked to the parent SampleViewer level. So when you launch the sample viewer level it is visible on the side bar. To accomplish this you need to first click Window->Levels-> and Add the flight sim level. and the other thing you need to do is add another entry in the SamplesDataTable for your level

2022-08-18 10:24 UTC, PauFlorenti commented
API key removed and top speed increased to x3 what it previously was.
I could not reproduce the airplane disappearing. Does it happen straight from the track at a distance? Or by doing a specific path or movement?
Level has been added to the sampler viewer level, but I found a few issues when restarting the level after crashing the plane regarding the API Key.

2022-08-18 16:08 UTC, PauFlorenti commented
@arash-sh  I've found an issue working in this sample. When loading the level from the sample viewer level, the mouse is not being captured for the movement of the ship. Any leads on why the mouse is not being captured?

2022-08-18 19:44 UTC, arash-sh commented
> @arash-sh I've found an issue working in this sample. When loading the level from the sample viewer level, the mouse is not being captured for the movement of the ship. Any leads on why the mouse is not being captured? 

In the SampleViewer level, the mouse is only captured when a mouse button is pressed. I think the controls should be changed in so that it behaves the same way in the standalone level. I also noticed that the SampleSelector UI is removed when the flight sim level is loaded. Is that OK @mrnelson6 ? 

Other comments:
- Possibly cap the rotation of the spaceship so that it doesn't become upside-down
- Shift button is a bit difficult to hold while pressing WASD. Possibly use W and S for acceleration/deacceleration since the mouse is already setting the pitch of the air plane. Alternatively, remove the controls for mouse so that both hands are on the keyboard and the right shift key (or any other key) can be used for acceleration
- When the level is restarted after crash, the API key should be re-applied to the map (e.g., the same way the SampleSelector does it)
- A unit for the speed in the UI would be good
- I think the way it is currently implemented, the altitude value would not be correct in a global scene.

2022-09-01 00:39 UTC, arash-sh commented
I don't know if it makes sense from the physics/realism point of view, but for me it feels more natural if the keys 'e' and 'q' only change the yaw rather than the whole rotation. Right now, for example, if the plane is tilted upwards and you hold 'e' it will end up pointing downwards. You can change this in the UpdateYaw function by using the up vector of the ENU transformation without multiplying it with the rotation of the ship mesh. But you should get the opinion of others on this as well. 

In the UpdateYaw/Pitch/Roll functions, I don't think the Lerp has an effect since the alpha value is constant. You can remove the lerp and adjust the speed value instead.

I wasn't able to run the flight simulator level (without loading it through sample selector). The plane falls through the surface before the map is loaded. I think you should place the Ship_BP in the scene instead of using the game mode 

When the plane crashes and the level is restarted there is a blueprint runtime error in the SampleSelector

If I remember right, this sample should use a global scene. This may cause some new problems that need to be fixed.

2022-09-09 13:38 UTC, PauFlorenti commented
The ship exploding at the beginning of the level is due to the elevation being enabled in the MapComponent, so to avoid the ship crashing at the beginning I am delaying the elevation of the map for a few seconds. The ideal would be to have a way for runtimecore to tell us if the map is fully loaded and then spawn the ship and start flying. Until that is not added we will stick with this solution.
- Disabling collisions for a few seconds may be another solution.

2022-09-13 11:11 UTC, airaolagoitia reviewed
It would be nice to improve the "flight dynamics" like when you want to go right, you'll press the right key (D or Arrow Right) and the plane will yaw to the right while rolling to the right as well. When you stop pressing the right key, it would stop rolling.

Do you think that is easy to implement?

2022-09-13 11:11 UTC, airaolagoitia commented on sample_project/Content/SampleViewer/Samples/FlightSimulator/readme.md
> +Keyboard Controls: Left Shift for Acceleration, Q for Yaw Left, E for Yaw Right, W or Mouse Y for pitch Up, S or Mouse Y for pitch down, A or Mouse X for roll left, D or Mouse X for roll right.
```suggestion
Keyboard Controls: Spacebar for Acceleration, Q for Yaw Left, E for Yaw Right, W or Mouse Y for Pitch Up, S or Mouse Y for Pitch Down, A or Mouse X for Roll Left, D or Mouse X for Roll Right. 
```

2022-09-13 11:11 UTC, airaolagoitia commented on sample_project/Content/SampleViewer/Samples/FlightSimulator/readme.md
> +H can be used to toggle the landing gear.
This doesn't work for me. Or I don't see anything happening.

2022-09-13 11:11 UTC, airaolagoitia commented on sample_project/Config/DefaultEngine.ini
> +GameInstanceClass=/Game/SampleViewer/BP_GameInstance.BP_GameInstance_C
will this affect other samples?

2022-09-13 11:11 UTC, airaolagoitia commented on sample_project/Config/DefaultInput.ini
> ++ActionMappings=(ActionName="Thrust",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=SpaceBar)
same. can these affect other samples?

2022-09-13 11:31 UTC, PauFlorenti commented on sample_project/Config/DefaultInput.ini
> ++ActionMappings=(ActionName="Thrust",bShift=False,bCtrl=False,bAlt=False,bCmd=False,Key=SpaceBar)
As far as I tested, this action mappings should not affect other samples since are only used in the flight simulator sample.

2022-09-13 11:38 UTC, PauFlorenti commented
> It would be nice to improve the "flight dynamics" like when you want to go right, you'll press the right key (D or Arrow Right) and the plane will yaw to the right while rolling to the right as well. When you stop pressing the right key, it would stop rolling.

Do you mean to roll and change pitch at the same time with just pressing a key? I don't think that is the way a plane should move, I believe we should give the option to roll, pitch and yaw independently.
We could add another key to do both roll and pitch at the same time though

2022-09-13 14:46 UTC, airaolagoitia approved these changes

2022-09-13 14:47 UTC, airaolagoitia commented
I think you should merge unless somebody else has comments. @mrnelson6 can review when he's back.

2022-09-15 11:26 UTC, tTakeda09 requested changes
I checked readme. It is just a suggestion and I might be wrong. So if there is any better way of explaining the sample, feel free to make your version.

2022-09-15 11:26 UTC, tTakeda09 commented on sample_project/Content/SampleViewer/Samples/FlightSimulator/readme.md
> +We add a physics **linear velocity** depending on the thrust and rotate for each of the axis adding a **torque** in such axis so that the plane can rotate in the roll, pitch and yaw axes. If the plan
```suggestion
2. Set the **Origin Position** for the place where you want to place the runway.
3. Create a runway and add it to the level. In this sample, the runway is created by using a cube and saved as **BP_Runway**.
4. Create a flying object as a **Pawn** and attach the [**ArcGIS Camera Component**](https://developers.arcgis.com/unreal-engine/maps/camera/#arcgis-camera-component) and [**ArcGIS Location Component**](https://developers.arcgis.com/unreal-engine/maps/location-component/).
5. Connect the flying object to the [**Player Controller**](https://docs.unrealengine.com/5.0/en-US/player-controllers-in-unreal-engine/) and place it on the map. In this sample, the flying object is saved as **BP_Ship**.
6. Work on [physics](https://docs.unrealengine.com/5.0/en-US/physics-in-unreal-engine/) from Unreal Engine's feature for the flying object. This sample uses [**Set Physics Linear Velocity**](https://docs.unrealengine.com/5.0/en-US/BlueprintAPI/Physics/SetPhysicsLinearVelocity/) for the speed control and [**Add Torque in Degrees**](https://docs.unrealengine.com/4.26/en-US/BlueprintAPI/Physics/AddTorqueinDegrees/) for the object's roll, pitch, and yaw. If the plane reduces enough its speed, false gravity drags the plane toward Earth.
```

This is how it looks like to me though I might be wrong...

2022-09-15 11:26 UTC, tTakeda09 commented on sample_project/Content/SampleViewer/Samples/FlightSimulator/readme.md
>  Controller Controls: Right Trigger for Acceleration, Left Trigger for Deceleration, Left Stick Left and Right for Yaw, Right Stick Left and Right for Roll, Right Stick up and down for Pitch. Right Th
I added the control to the How to use the sample section above.

2022-09-15 15:34 UTC, PauFlorenti commented on sample_project/Content/SampleViewer/Samples/FlightSimulator/readme.md
> +H can be used to toggle the landing gear.
```suggestion
```

2022-09-15 15:34 UTC, PauFlorenti commented on sample_project/Content/SampleViewer/Samples/FlightSimulator/readme.md
>  Controller Controls: Right Trigger for Acceleration, Left Trigger for Deceleration, Left Stick Left and Right for Yaw, Right Stick Left and Right for Roll, Right Stick up and down for Pitch. Right Th
```suggestion
```

2022-09-16 11:41 UTC, tTakeda09 approved these changes

2022-09-21 13:49 UTC, airaolagoitia commented
@mrnelson6 can you give this a look before we merge it?

2023-09-12 00:57 UTC, Jade-JadeH commented
I'm checking this PR today to see if we should close or keep it. but was not able to compile this with 1.0.0 (which is what this was built for). @PauFlorenti Do you think it's worthwhile to make this to work with the current version? 

![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/86364673/98f30486-9d34-4da5-8db8-471e42b05234)

2023-09-13 13:02 UTC, airaolagoitia commented
@Jade-JadeH that error is probably due to an unclean setup

2023-09-13 16:45 UTC, Jade-JadeH commented
@airaolagoitia I did try a clean setup by removing all unnecessary folders and the VS file

2023-09-20 11:36 UTC, airaolagoitia commented
@Jade-JadeH I tested Pau's branch with 1.3. The only issues I got were:
* in `sample_project\Source\sample_project\Routing\RouteManager.cpp` where the deprecated `GetAPIkey` was being used. We need to use `GetAPIKey`.
* a similar one in a blueprint..

both easily fixable.. I wasn't able to push the fixes probably because this is in Pau's account repo.

2023-09-21 17:57 UTC, Jade-JadeH commented
@airaolagoitia Ok thanks was able to get that to work, still have other two issues @PauFlorenti which is that 

1. when you open the flightsim level, and put API key in the ArcGISMapActor, you get the "Game Instance has no valid widget menu!" error and plane just crashed. This error doesn't occur when you open from the sample viewer level. 
2. the H key doesn't work 

Other than this the sample looks great. I do think that when the speed drops the plane's falling speed needs to be faster  @avr757 also the UI needs to be reworked too

2024-06-17 20:06 UTC, closed without merging