Jad10309/measure
Esri/arcgis-maps-sdk-unreal-engine-samples pull request #21
Opened 2022-08-30 03:03 UTC by Jade-JadeH

**Sample**

**Summary**

**Tests**

**ArcGIS Maps SDK Version**

2022-09-07 11:52 UTC, airaolagoitia reviewed
I see multiple formatting issues. Should we copy our clang-format file to this repo?

2022-09-07 17:21 UTC, tTakeda09 commented
> I see multiple formatting issues. Should we copy our clang-format file to this repo?

If it's just copy & paste, it would be nice, I'd say.

2022-09-07 17:22 UTC, Jade-JadeH commented
> I see multiple formatting issues. Should we copy our clang-format file to this repo?

sounds good.

2022-09-07 17:28 UTC, tTakeda09 requested changes
I don't see the Readme file in this PR and until you have the readme it's better not to merge this to main.

I also have a question. I see changes on other samples in this PR, removing `Routing.umap` for example. Is that OK?

2022-09-07 17:30 UTC, Jade-JadeH commented
> I don't see the Readme file in this PR.
> 
> I also have a question. I see changes on other samples in this PR, removing `Routing.umap` for example. Is that OK?

> got caught, was gonna fix those two things you mentioned now

2022-09-07 19:00 UTC, Jade-JadeH commented
> I don't see the Readme file in this PR and until you have the readme it's better not to merge this to main.
> 
> I also have a question. I see changes on other samples in this PR, removing `Routing.umap` for example. Is that OK?

fixed these two issues

2022-09-13 02:21 UTC, NaumanIsGISMan requested changes
Apologies ahead of time Jade, there's a bunch of styling fixes that need to get done here. I would run the clang formatter first on the two source files and commit that change, then go through the individual suggestions

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +		for (auto point : SplineMeshComponents) {
Spaces and bracket for each logic chunk

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +}
```suggestion
}

```

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +	InputComponent = NewObject<UInputComponent>(this);
Is `InputComponent` inherited?

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +	float traceLength = 10000000.f;
This and the other `traceLength` in `SetElevation` could be a `constexpr` that lives at the top of this file. It also probably just makes sense to inline it into the `LineTraceSingleByChannel` function

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +		position + traceLength * direction, ECC_Visibility, FCollisionQueryParams());
This formatting seems odd

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +		auto lineMarker = GetWorld()->SpawnActor<ARouteMarker>(ARouteMarker::StaticClass(), hit.ImpactPoint, FRotator(0.f), SpawnParam);
It could be `0.0f` or just `0`
```suggestion
		auto lineMarker = GetWorld()->SpawnActor<ARouteMarker>(ARouteMarker::StaticClass(), hit.ImpactPoint, FRotator(0.0f), SpawnParam);
```

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +		}
```suggestion
		}

```

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +			double d = UArcGISGeometryEngine::DistanceGeodetic(lastPoint, thisPoint, unit, UArcGISAngularUnit::CreateArcGISAngularUnit(EArcGISAngularUnitId::Degrees), EArcGISGeodeticCurveType::Geodesic)->GetD
`d` should be like `distance` or something more clear

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +			geodeticDistanceText = FString::Printf(TEXT("Distance: %f %s"), round(geodeticDistance * 1000.0) / 1000.0, *unitTxt);
It might make more sense to make this local a local var with `auto`

```suggestion
			auto geodeticDistanceText = FString::Printf(TEXT("Distance: %f %s"), round(geodeticDistance * 1000.0f) / 1000.0f, *unitTxt);
```

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +			float n = floor((float)d / InterpolationInterval);
Can you rename these vars to something that makes more sense?

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +		USplineMeshComponent* SplineMesh;
```suggestion
		USplineMeshComponent* SplineMesh;

```

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +			tangent = tangent * 100.;
```suggestion
			tangent = tangent * 100.0f;
```

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +}
```suggestion
}

```

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +	float traceLength = 1000000.f;
```suggestion
	float traceLength = 1000000.0f;
```

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +	float elevationOffset = 200.;
```suggestion
	float elevationOffset = 200.0f;
```

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +	position.Z = bTraceSuccess ? hitInfo.ImpactPoint.Z + elevationOffset : 0.;
```suggestion
	position.Z = bTraceSuccess ? hitInfo.ImpactPoint.Z + elevationOffset : 0.0f;
```

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +		currentUnit = m;
Where is `m` coming from? Can you rename it?

2022-09-13 02:21 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +	}
```suggestion
	}

```

2022-09-13 23:49 UTC, Jade-JadeH commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +		currentUnit = m;
you mean use "meter?"

2022-09-14 03:03 UTC, Jade-JadeH commented on sample_project/Source/sample_project/Measure/Measure.h
> +
good to know!

2022-09-14 03:05 UTC, Jade-JadeH commented on sample_project/Source/sample_project/Measure/Measure.h
> +	UArcGISMapComponent* MapComponent;
Thanks!

2022-09-14 03:13 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +		currentUnit = m;
Yeah, I would rename the variable to something more clear

2022-09-14 05:29 UTC, Jade-JadeH commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +			geodeticDistanceText = FString::Printf(TEXT("Distance: %f %s"), round(geodeticDistance * 1000.0) / 1000.0, *unitTxt);
this one is used by multiple functions, for example in `unitChanged`, whenever the unit selector detects a unit change geodeticDistanceText gets updated (1 miles -> 1.6 kilometers)

2022-09-16 18:15 UTC, NaumanIsGISMan requested changes

2022-09-16 18:15 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +		Unit = UArcGISLinearUnit::CreateArcGISLinearUnit(EArcGISLinearUnitId::Meters);
Each one of the code in each `if` and `else if` statement can be refactored into a method, something like

```cpp
void AMeasure::SetWidgetUnits(EArcGISLinearUnitId Id,  currentUnit, const FString& Text)
{
		Unit = UArcGISLinearUnit::CreateArcGISLinearUnit(Id);
		GeodeticDistance = ConvertUnits(GeodeticDistance, CurrentUnit, currentUnit);
		CurrentUnit = currentUnit;
		UnitText = Text;
}

```

2022-09-16 18:15 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.h
> +#include "ArcGISMapsSDK/Actors/ArcGISMapActor.h"
nitpick: order

2022-09-16 18:15 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +			SplineMeshComponents.AddHead(SplineMesh);
This should be refactored into a method

2022-09-16 18:15 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +				pre = next->GetActorLocation();
This should be refactored into a method

2022-09-16 18:15 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +
This whole chuck should be refactored into a method

2022-09-16 18:24 UTC, Jade-JadeH commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +				pre = next->GetActorLocation();
I'd want it be more encapsulated too. This was a separate method called "Interpolate" in unity, but since this all react to "left shift and click", I put it under `AddStop()` and bind the key to `AddStop()` in 

```
if (InputComponent)
{
	InputComponent->BindAction("PlaceRoutePoint", IE_Pressed, this, &AMeasure::AddStop);
	EnableInput(GetWorld()->GetFirstPlayerController());
}
```

this is the same with the routing sample which also put together different chunks of code under `AddStop()` method. I wonder if there's a way to separate them?

2022-09-16 18:26 UTC, Jade-JadeH commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +
same as above

2022-09-16 18:27 UTC, Jade-JadeH commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +			SplineMeshComponents.AddHead(SplineMesh);
same below, in Unity it's a different method called `RenderLine()` , let me see if I can do the same in unreal

2022-09-16 21:18 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +				pre = next->GetActorLocation();
Yeah, I think everything in the two if statements could be broken out into two methods. At least it'll make things easier to read

2022-09-16 21:38 UTC, airaolagoitia commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +	ConstructorHelpers::FObjectFinder<UStaticMesh> MeshAsset(TEXT("/Game/SampleViewer/Samples/Routing/Geometries/Cube.Cube"));
What about using Unreal's?

`"StaticMesh'/Engine/BasicShapes/Cube.Cube'"`

2022-09-16 21:38 UTC, airaolagoitia commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +	ConstructorHelpers::FObjectFinder<UClass> WidgetAsset(TEXT("/Game/SampleViewer/Samples/Measure/Blueprints/UI_Measure.UI_Measure_C"));
can we use `UUserWidget` instead of `UClass`?

2022-09-16 21:38 UTC, airaolagoitia commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +	APlayerController* playerController = UGameplayStatics::GetPlayerController(GetWorld(), 0);
```suggestion
auto playerController = UGameplayStatics::GetPlayerController(GetWorld(), 0);
```

2022-09-16 21:38 UTC, airaolagoitia commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +	APlayerController* PlayerController = UGameplayStatics::GetPlayerController(GetWorld(), 0);
auto

2022-09-16 21:38 UTC, airaolagoitia commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +			//calculate distance from last point to this point
```suggestion
			// Calculate distance from last point to this point
```

2022-09-16 21:38 UTC, airaolagoitia commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +			//interpolate points between last point/start and this point(end)
```suggestion
			// Interpolate points between last point/start and this point(end)
```

2022-09-16 21:38 UTC, airaolagoitia commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +			//calculate numInterpolation intepolation points/n segments because the last segment is already created by the end point
```suggestion
			// Calculate numInterpolation interpolation points/n segments because the last segment is already created by the end point
```

2022-09-16 21:38 UTC, airaolagoitia commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +				//calculate transform of next point
```suggestion
				// Calculate transform of next point
```

2022-09-16 21:38 UTC, airaolagoitia commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +				//define height
same

2022-09-16 21:38 UTC, airaolagoitia commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +double AMeasure::ConvertUnits(double value, UnitType from, UnitType to)
Seems format is not being applied

```suggestion
}

double AMeasure::ConvertUnits(double value, UnitType from, UnitType to)
```

2022-09-16 21:38 UTC, airaolagoitia commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +}
Empty EOF

2022-09-16 21:38 UTC, airaolagoitia commented on sample_project/Source/sample_project/Measure/Measure.h
> +	meters = 0,
UpperCamelCase?

2022-09-16 21:38 UTC, airaolagoitia commented on sample_project/Source/sample_project/Measure/Measure.h
> +};
E EOF

2022-09-20 23:22 UTC, mrnelson6 requested changes
- Convert to function can be removed
- Can you reduce the intensity of the directional light in the measure scene? It feels like the breadcrums and nodes are too bright 
- We can put shared resources (M_Breadcrumb.uasset) into the sharedResources folder if multiple samples are going to use it

@airaolagoitia there seems to be some sort of lifecycle/read access violation coming from the `TObjectPtr<UArcGISLinearUnit> Unit;`  If you place a bunch of stops and let it idle for a while the next time you add a stop we get the crash. Still looking into it at the moment.

2022-09-20 23:22 UTC, mrnelson6 commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +double AMeasure::ConvertUnits(double value, UnitType from, UnitType to)
We don't need this function. UArcGISLinearUnit has functions on it already to convert to other Units

double ConvertTo(UArcGISLinearUnit* toUnit, double value) const;

2022-09-26 00:44 UTC, Jade-JadeH commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +	ConstructorHelpers::FObjectFinder<UStaticMesh> MeshAsset(TEXT("/Game/SampleViewer/Samples/Routing/Geometries/Cube.Cube"));
our cube is colored..

2022-09-26 01:52 UTC, Jade-JadeH commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +	ConstructorHelpers::FObjectFinder<UClass> WidgetAsset(TEXT("/Game/SampleViewer/Samples/Measure/Blueprints/UI_Measure.UI_Measure_C"));
not sure why but if I change it to `UUserWidget` the type is not correct

2022-09-26 05:18 UTC, Jade-JadeH commented
> * Can you reduce the intensity of the directional light in the measure scene? It feels like the breadcrums and nodes are too bright
I lowered the intensity. I forgot to mention that I change the colors of breadcrumbs and markers so they're not green and red anymore. They're more like grapefruit red and blueish green now which appear to be washed out.

2022-09-26 05:53 UTC, Jade-JadeH commented
@mrnelson6 since I moved some assets to shared resources, I changed the file path in the routing sample code so there're two lines changes there.

2022-09-27 21:31 UTC, NaumanIsGISMan approved these changes

2022-09-28 16:15 UTC, Jade-JadeH commented
@airaolagoitia I need your's ok to be able to merge

2022-09-28 20:48 UTC, airaolagoitia commented
> @airaolagoitia I need your ok to be able to merge

I'll review in a moment but I'm not the one blocking the merge. It's @tTakeda09

2022-09-28 23:23 UTC, airaolagoitia approved these changes
Minor comments otherwise looks good.

2022-09-28 23:23 UTC, airaolagoitia commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +/* Copyright 2022 Esri
This header looks different than the one in the header. Is that correct?

2022-09-28 23:23 UTC, airaolagoitia commented on sample_project/Source/sample_project/Measure/Measure.h
> +#pragma once
nitpick

```suggestion
// email: legal@esri.com
#pragma once
```

2022-09-29 04:09 UTC, Jade-JadeH commented on sample_project/Source/sample_project/Measure/Measure.cpp
> +/* Copyright 2022 Esri
You're right, changed

2022-09-29 04:23 UTC, Jade-JadeH commented
> I'll review in a moment but I'm not the one blocking the merge. It's @tTakeda09

       sorry wasn't able to tell, but thanks for reviewing.

2022-09-29 13:39 UTC, airaolagoitia commented
> > I'll review in a moment but I'm not the one blocking the merge. It's @tTakeda09
> 
> sorry wasn't able to tell, but thanks for reviewing.

You should see this below
![image](https://user-images.githubusercontent.com/53488136/193047094-70a354f7-873b-4e85-9b9e-efeaad7c366e.png)

2022-10-03 22:48 UTC, Jade-JadeH commented
@tTakeda09 I changed according to your comment, could you rereview

2022-10-04 15:20 UTC, tTakeda09 approved these changes
Readme now looks good to me.

2022-10-04 15:23 UTC, tTakeda09 commented on sample_project/Content/SampleViewer/Samples/Measure/readme.md
> +2. Set your API Key in the **ArcGIS Map** game object using the **Inspector** window.
Sorry, I approved but I just realized that this is UE sample. So the wordings need to be updated for UE.

game object -> Actor
Inspector window -> Details panel.

2022-10-04 18:42 UTC, merged