Mas12517/user interface/3rd person UI
Esri/arcgis-maps-sdk-unreal-engine-samples pull request #46
Opened 2023-07-06 23:09 UTC by mmgaw113

**Sample**

Redo of Third Person Sample and Third Person Sample Directions User Interface

**Summary**

- Recreate the third person sample using C++ for better performance
- Add Flying ability to Third Person Character
- Swap Character mesh for Map Man from UE5 Mannequin
- Third Person Usage Directions UI created and Implemented 

**Tests**

Windows

**ArcGIS Maps SDK Version**

UE 5.0 with Maps SDK 1.2

2023-07-10 16:38 UTC, dan13436 commented
Playtested in the editor! Flying around the city feels really good, transitioning between walking and flying is smooth, and the UI is clear and digestible, very well done! My only nitpick is that the camera sometimes jitters when you go to fast but that could be negligible.

2023-07-14 00:00 UTC, avr757 commented
UI nitpick

1. The minimized pop-up window icon is looking super blurry. What resolution did you export it at? You should try to export it at a higher resolution. I'm not sure if Unreal allows SVG. If it does, SVG would be the better choice as it's vector based.
![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/f057b2cd-be41-450c-9314-27e9de64354e)
2. Also, can you leave some margin around the icon? You can try to reduce the size by 15%-20%. If you compare with the design in Figma, you'll see that there is a plenty of margin around the purple box.
![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/513a0803-f75d-457e-9473-6edcead9366b)
3. I made a new design to cater some of the extra keys you added. When we have many keys, it will look cleaner to make the arrangement more "listing" like. I reduced some of the key sizes and tried to make it look less busier.
![Instruction - 3rd person controller](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/d23757b9-9be9-40fd-a8e3-2418ff715ed6)
4. Couple of design things to change around. Note: all the keys should have equal height to make the look more visually consistent.
![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/2acae050-1a3a-43fd-b167-9fe614beda1d)
5. What if we make a fly toggle with the same key? Say the "F" key is to toggle fly mode. Reduce the number of key controls when possible can not only help with cleaning up the UI instructions menu but also give users less keys to worry about.

2023-07-14 00:01 UTC, avr757 requested changes
UI nitpick

1. The minimized pop-up window icon is looking super blurry. What resolution did you export it at? You should try to export it at a higher resolution. I'm not sure if Unreal allows SVG. If it does, SVG would be the better choice as it's vector based.
![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/f057b2cd-be41-450c-9314-27e9de64354e)
2. Also, can you leave some margin around the icon? You can try to reduce the size by 15%-20%. If you compare with the design in Figma, you'll see that there is a plenty of margin around the purple box.
![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/513a0803-f75d-457e-9473-6edcead9366b)
3. I made a new design to cater some of the extra keys you added. When we have many keys, it will look cleaner to make the arrangement more "listing" like. I reduced some of the key sizes and tried to make it look less busier.
![Instruction - 3rd person controller](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/d23757b9-9be9-40fd-a8e3-2418ff715ed6)
4. Couple of design things to change around. Note: all the keys should have equal height to make the look more visually consistent.
![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/2acae050-1a3a-43fd-b167-9fe614beda1d)
5. What if we make a fly toggle with the same key? Say the "F" key is to toggle fly mode. Reduce the number of key controls when possible can not only help with cleaning up the UI instructions menu but also give users less keys to worry about.

2023-07-14 00:06 UTC, avr757 commented
also noticed that the Map Man jitters a bit when flying.


https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/e7b943c8-c521-4512-a77c-400160887a30

2023-07-14 21:38 UTC, SamCartledge commented
> also noticed that the Map Man jitters a bit when flying.
> 
I believe this is a affected by your computer's performance because I did not notice this

2023-07-14 21:46 UTC, mmgaw113 commented
> > also noticed that the Map Man jitters a bit when flying.
> 
> I believe this is affected by your computer's performance because I did not notice this

Agreed. I noticed it on my personal work laptop but it was not an issue demoing it at UC nor is it an issue on my personal computer with a 3080 in it. We can have zack test is on the Alienware or Daniel on adriens computer to verify this

2023-07-14 21:57 UTC, avr757 commented
yeah I was gonna say I remembered at the UC it was running real smooth. @SamCartledge do you roughly remember what the spec was for the UC demo PC? I am running it on a Xeon w-2235 w/ Quadro P2200. I think it would be interesting to find out or get a general sense of at what spec will this run well.

2023-07-17 16:08 UTC, mmgaw113 commented
Try running the scene in "Selected Viewport" instead of "Standalone Window", and turn "show FPS" on. He jitters during frame drops. Both of those should help

2023-07-17 16:51 UTC, mmgaw113 commented on sample_project/Source/sample_project/ThirdPerson/ThirdPersonCharacter.h
> +	virtual void Tick(float DeltaTime) override;
The functions I made private since I don't need to call any of them from blueprints, but the input components need to be public since I have to set them in editor. Making them private would mean I need to remove them being blueprint accessible. Just learned that today XD

2023-07-18 00:58 UTC, avr757 requested changes
Besides the layout and blurriness of the icons, 4) from the previous comment list has not been all addressed.

![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/0af008c4-6114-4cf0-8501-ab8fb2049cc8)

![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/a70140cc-b1f2-4ae7-aef9-b4107e74b8dc)

We will also need to ask other people to test 3rd person on more computers regarding the jitter issues.

2023-07-18 17:40 UTC, mmgaw113 commented
@avr757 I'm not seeing any blurry images, they are all set at their native resolution and then scaled down. They look normal on my monitor and I testing in different view modes to make sure it wasn't a specific mode issue. Is there a specific image that looked blurry?

The rest of the UI layout issues I just pushed.

2023-07-18 23:59 UTC, avr757 commented
> @avr757 I'm not seeing any blurry images, they are all set at their native resolution and then scaled down. They look normal on my monitor and I testing in different view modes to make sure it wasn't a specific mode issue. Is there a specific image that looked blurry?
> 
> The rest of the UI layout issues I just pushed.

It's not blurry anymore after your "Replace Info Image" commit. I was trying to say "Besides the layout and blurriness of the icons (that you've already addressed), 4) from the previous comment list has not been all addressed."

2023-07-19 00:14 UTC, avr757 requested changes
![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/d8791962-6343-4f0a-bd05-683224953982)

Getting really close! Some of my previous feedback still haven't been addressed though:

1) When you put "Press G to show cursor" down at the bottom, it leaves no margin space. So that should go on top for better alignment/organization.
2) F, Ctrl, Shift keys should line up on the right side.
3) WASD keys and space key are too close to the left edge near the purple part (margin space is too tight). Also make sure the vertical spaces between them are equal.
4) Can you please follow this one below? it will make things so much easier instead of me keeping repeating the same thing over :sweat_smile: If you have different design ideas, I'm definitely open to more discussions. 

![Instruction - 3rd person controller](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/d23757b9-9be9-40fd-a8e3-2418ff715ed6)

2023-07-19 01:01 UTC, avr757 commented
Also the opacity of the instruction menu background should be set to around 85%

2023-07-19 15:45 UTC, mmgaw113 commented
> Also the opacity of the instruction menu background should be set to around 85%

The Grey you have listed for this does not work in unreal. When I plug in #0A0A0A it makes the color black and 0% opacity. Not sure if this is the wrong color or if unreal just really doesn't like it.

2023-07-19 17:08 UTC, merged