Mas12517/feature layer redesign
Esri/arcgis-maps-sdk-unreal-engine-samples pull request #50
Opened 2023-08-21 15:07 UTC by mmgaw113

**Sample**

Feature Layer Redesign

**Summary**

This sample aids to add functionality to the Original Feature Layer Sample that allows users to customize the data being queried. 

The link provided in the sample is [here](https://services.arcgis.com/V6ZHFr6zdgNZuVG0/ArcGIS/rest/services/ParkTrees/FeatureServer/0/Query?f=geojson&where=1=1&outfields=*)

You may swap the link out for the [baseball stadiums](https://services.arcgis.com/P3ePLMYs2RVChkJx/ArcGIS/rest/services/Major_League_Baseball_Stadiums/FeatureServer/0/Query?f=geojson&where=1=1&outfields=*) (or any other feature layer) at any time

- Please test valid links (put something like https://google.com in and it should give you a warning)
- When you change to a different feature layer, don't change the outfields and it should give a warning
- Uncheck the "Get All Samples" box but leave the index at 0 - 175 and it should give a warning

**Feature Layer Blueprint**
- This blueprint is called bp_feature and is already in the scene. 
- If you click on it you should see this 
![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/89485705/4b8b61a9-9429-426a-88a6-4ae2135aeb00)

- Clicking on outfields will show the outfields the user is getting. You may change these at anytime to valid outfields associated with the feature layer you are querying. If you would like to see what the outfields are on the feature layer, go to your feature layer in your web browser and set the outfields to **"outfields=*"** and this will query all of the outfields.

**Objects Spawned In**
- If you set the outfields to valid outfields, you can click on the objects and there will be an array called "Feature Data"
- If you click the array to open it, it should show the data it got from the feature layer query

**Tests**

Windows

**ArcGIS Maps SDK Version**

UE 5.0 with Maps SDK 1.2 & 1.3

2023-08-22 22:54 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.h
> +	int startValue;
```suggestion
	int StartValue;
```

2023-08-22 22:54 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.h
> +	int lastValue;
```suggestion
	int LastValue;
```

2023-08-22 22:54 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.h
> +	bool bLinkReturnError;
I would group the bools all together

2023-08-22 22:54 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.h
> +	void CreateLink();
Move and consolidate this public section with the one above, alphabetical, functions first

2023-08-22 22:54 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.h
> +	UPROPERTY(BlueprintReadWrite, EditAnywhere)
Do these properties need to be public? Looks like you can make a lot of them private

2023-08-22 22:54 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.h
> +	AArcGISPawn* ArcGisPawn;
```suggestion
	AArcGISPawn* ArcGISPawn;
```

2023-08-22 22:54 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.h
> +	TArray<FString> featureProperties;
```suggestion
	TArray<FString> FeatureProperties;
```

2023-08-22 22:54 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.h
> +	TArray<float> geoProperties;
```suggestion
	TArray<float> GeoProperties;
```

2023-08-22 22:54 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.h
> +struct SAMPLE_PROJECT_API FProperties
`FProperties` might be too generic.
```suggestion
struct SAMPLE_PROJECT_API FFeatureLayerProperties
```

2023-08-22 22:54 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.h
> +	FString headers;
`UpperCamelCase` for these public props

2023-08-22 22:54 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.cpp
> +// Called when the game starts or when spawned
```suggestion
```

2023-08-22 22:54 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.cpp
> +		for (auto property : feature.featureProperties)
The naming here is odd. Can you consolidate this loop? Is `Element` the same type as `FProperties`?
```
for (auto data : FeatureData)
{
	for (auto property : data.featureProperties)
```

2023-08-22 22:54 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.cpp
> +				for(auto outfield : WebLink.outFields)
```suggestion
				for (auto outfield : WebLink.outFields)
```

2023-08-22 22:54 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.cpp
> +		for (auto property : feature.featureProperties)
Also looks like these could be `const auto`

2023-08-22 22:54 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.cpp
> +				TSharedPtr<FJsonObject> properties = feature->GetObjectField("properties");
can be autos? const autos?

2023-08-22 22:54 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.cpp
> +		TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(ResponseBody);
auto?

2023-08-23 01:07 UTC, mmgaw113 commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.h
> +	UPROPERTY(BlueprintReadWrite, EditAnywhere)
Yes, Blueprint read write properties can't be private. But some aren't edit anywhere so I'll move them around

2023-08-23 01:18 UTC, mmgaw113 commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.cpp
> +		for (auto property : feature.featureProperties)
I don't know if these can be consolidated... The first loop is getting each Feature in Feature Data. Then the second loop is getting the array in the struct of FeatureProperties. So I am not sure if consolidating is possible. Tips or pointers if you know of a way would be much appreciated.

2023-08-23 01:23 UTC, mmgaw113 commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.cpp
> +		TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(ResponseBody);
Line 33 requires initialization if using auto

2023-08-24 18:32 UTC, Jade-JadeH commented
1. I tried this one https://runtime.maps.arcgis.com/home/item.html?id=d957997ccee7408287a963600a77f61f with this URL https://services9.arcgis.com/RHVPKKiFTONKtxq3/arcgis/rest/services/USA_Wildfires_v1/FeatureServer and, and also this one https://runtime.maps.arcgis.com/home/item.html?id=248e7b5827a34b248647afb012c58787 with this URL https://services9.arcgis.com/RHVPKKiFTONKtxq3/arcgis/rest/services/Active_Hurricanes_v1/FeatureServer and didn't work.

2. When I enter the service the map moves 

3. Can you add a loading indicator and error indicator in the note banner like this one? Or, you could change "Process Request" to "loading" when user inputs a data

![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/86364673/ac32b26e-5fba-4b3a-8430-47771b142f80)

4. there's still this instruction here, maybe you plan to fix it on another PR: 
![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/86364673/3316f4dd-c7cc-4525-a007-c0558526e8fc)

5. there's no index filtering compared with this PR https://devtopia.esri.com/runtime/normandy/issues/2161#issuecomment-4283144

Nitpicking:
1. The use of pin doesn't seem to make as much sense as routing and geolocating samples @avr757 any ideas?

2023-08-24 18:42 UTC, Jade-JadeH commented
Testing this feature service https://runtime.maps.arcgis.com/home/item.html?id=d957997ccee7408287a963600a77f61f with the URL https://services9.arcgis.com/RHVPKKiFTONKtxq3/arcgis/rest/services/USA_Wildfires_v1/FeatureServer doesn't work, tested a couple others and don't work either

2023-08-24 18:49 UTC, mmgaw113 commented
> Testing this feature service https://runtime.maps.arcgis.com/home/item.html?id=d957997ccee7408287a963600a77f61f with the URL https://services9.arcgis.com/RHVPKKiFTONKtxq3/arcgis/rest/services/USA_Wildfires_v1/FeatureServer doesn't work, tested a couple others and don't work either (个_个)

Add “/query?” To the link and it should work. I’ll add it to the code but it currently assumes you will add “query?”

2023-08-24 19:47 UTC, mmgaw113 commented
The UI we plan to address in a future PR, this is just for functionality because it was such a massive task/issue, we wanted to split the UI apart from it. Right now, I just want to make sure everything is working properly and then I will disable the old UI before it gets merged in. 

I don't know if anything else makes sense other than a pin at the moment. We changed the default link out to be trees instead of baseball stadiums but if we make the static mesh a tree, then users might not know how to change it to be what they want. So I think leaving it as a pin makes the most sense for now.

2023-08-24 20:04 UTC, mmgaw113 commented
> 1. When I enter the service the map moves

So I would need to see what you are talking about to understand but there are two things I can think of. Pasting the link into the search bar by hitting "ctrl + v" moves the camera downward. crtl is one of the input mappings for the arcgis Pawn and moves the camera down. 

Alternatively, when you process the request, it randomly picks a point from the feature layer and moves the camera to it.

2023-08-24 21:03 UTC, Jade-JadeH commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.cpp
> +	else if(!WebLink.Link.Contains("f=geojson&where=1=1"))
```suggestion
	else if(!WebLink.Link.Contains("f=geojson&where=1=1&outfields=*"))
```

2023-08-24 21:15 UTC, dan13436 approved these changes
I am not too knowledgeable on feature layers yet, but from what I could gather it seemed like it was working. The lack of UI feedback on top of my ignorance did make it hard to manage, but it seems like the functionality is all there. Concatenating the "/0/query?" through code helped a lot; seems to work with Jades link

2023-08-24 21:19 UTC, dan13436 commented
Would definitely hold off on other approvals before merging, I could have missed something

2023-08-24 22:33 UTC, avr757 commented
> 1. The use of pin doesn't seem to make as much sense as routing and geolocating samples @avr757 any ideas?

I think the pin is generic enough for now, but if we want to make it more fun and entertaining in the future, we could use lollipop models instead.

![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/5e63f05b-13c0-4289-94a9-9b452b0b2efa)

2023-08-24 22:36 UTC, Jade-JadeH commented
so the URL still doesn't work for me, the concatenation seems to add additional outfields:
![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/86364673/5f1729ab-70bd-4018-b8bb-3a2082b31a48)

2023-08-24 22:36 UTC, mmgaw113 commented
> so the URL still doesn't work for me, the concatenation seems to add additional outfields: ![image](https://user-images.githubusercontent.com/86364673/263120806-5f1729ab-70bd-4018-b8bb-3a2082b31a48.png)

what are you pasting in for the URL?

2023-08-24 22:37 UTC, Jade-JadeH commented
> bout to understand but there are two things I can think of. Pasting the link into the search bar by hitting "ctrl + v" moves the camera downward

Both of them. But sounds good that you'll fix it during UI.

2023-08-24 23:00 UTC, mmgaw113 commented
@Jade-JadeH I swapped the concatenation to a foreach loop. The loop will return invalid link if it does not end in outfields=*. The link will not work if it is not in the correct order of /0/query?f=geojson&where=1=1&outfields=*
I just set it up so that it returns an error now if this happens and will ask you to fix your link.

It should be good for you to take a look again

2023-08-25 02:47 UTC, Jade-JadeH commented
I tried this page https://runtime.maps.arcgis.com/home/item.html?id=9e2f2b544c954fda9cd13b7f3e6eebce (with this URL https://services9.arcgis.com/RHVPKKiFTONKtxq3/arcgis/rest/services/USGS_Seismic_Data_v1/FeatureServer).

I got different results which are the follow:

1. Data is not aligned with the terrain

I had this before when I worked on the feature layer sample. This is due to mesh being spawned before terrain is loaded. 

![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/86364673/3224b2ce-5280-4e67-adfd-7b99ca2d3300)

2. an empty warning and no data is displayed:

![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/86364673/0af1a5ce-de45-401a-8c4a-0ddc648e34f9)

3. Data is loaded 

In this case, I noticed that we just zoom to a data point, but instead I think we should "zoom to layer" otherwise it's really hard to get an overview of the data.

2023-08-25 02:52 UTC, Jade-JadeH commented
I also tried this page https://runtime.maps.arcgis.com/home/item.html?id=0ec8512ad21e4bb987d7e848d14e7e24 and unreal crashed.

2023-08-25 18:01 UTC, mmgaw113 commented
> I also tried this page https://runtime.maps.arcgis.com/home/item.html?id=0ec8512ad21e4bb987d7e848d14e7e24 and https://runtime.maps.arcgis.com/home/item.html?id=a98fd08751a5480c898b7cebe38807f4 (not with these two URLs, with the URLs inside the pages)
> 
> and it gives me a warning "URL is not valid" and unreal crashes.

This link isn't going to work because it isn't in the same format as the others. Currently the sample only supports specific types of feature layers, I forget the type but @ZackAllen and I talked a bit about it. We want to support more types in the future but this is already a big enough task as is so we will split it up into smaller tasks once we get both unity and unreal primary functionality working.

2023-08-25 21:26 UTC, Jade-JadeH commented
> This link isn't going to work because it isn't in the same format as the others. Currently the sample only supports specific types of feature layers, I forget the type but @ZackAllen and I talked a bit about it. We want to support more types in the future but this is already a big enough task as is so we will split it up into smaller tasks once we get both unity and unreal primary functionality working.

Can you add which data is not supported? And prevent crashes?

2023-08-28 16:44 UTC, mmgaw113 commented
> Can you add which data is not supported? And prevent crashes?

Crashes I should be able to avoid. I think we should put what data types are supported in the instructions when we redo the UI.
It only supports Point Feature Layer Data I believe. The ones you were trying are polygon

2023-08-28 17:49 UTC, mmgaw113 commented
Crashes are fixed, the error notification also goes away now if there are no errors. It also checks the type of data now in the script so it should give an error if the data type is unsupported.

2023-08-28 21:42 UTC, NaumanIsGISMan approved these changes
Looks good code wise beside some minor nits

2023-08-28 21:42 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.cpp
> +		for (const auto property : feature.FeatureProperties)
You shouldn't have to need to create a separate local var

```suggestion
	for (const auto feature : FeatureData)
	{		
		for (const auto property : feature.FeatureProperties)
```

2023-08-28 21:42 UTC, NaumanIsGISMan commented on sample_project/Source/sample_project/Feature Layer/FeatureLayer.cpp
> +				TArray<TSharedPtr<FJsonValue>> coordinates = feature->GetObjectField("geometry")->GetArrayField("coordinates");
Can this be auto?
```suggestion
				auto coordinates = feature->GetObjectField("geometry")->GetArrayField("coordinates");
```

2023-08-28 22:13 UTC, ZackAllen requested changes
Tested with a feature layer from AGOL and had working results.

Request:
- The current instructions image is invalid in the new workflow. We should delete it and replace it with something correct until the new UI is ready.

Suggestions:
- This code is pretty important, I think we should add more comments explaining how features are parsed from the response.
- Add debug message for unsupported geometry. (Instructions should also mention only point geometry is currently supported)

2023-08-29 16:31 UTC, ZackAllen approved these changes

2023-08-29 16:36 UTC, merged