Readme cover image update
Esri/arcgis-maps-sdk-unreal-engine-samples pull request #53
Opened 2023-09-12 15:59 UTC by avr757

Update readme cover images to all samples.

- Unified cover image sizes to 1280x720 res
- Changed all image format to .png
- Changed readme files

2023-09-12 16:24 UTC, ZackAllen requested changes

2023-09-12 16:24 UTC, ZackAllen commented on sample_project/Content/SampleViewer/Samples/Measure/readme.md
>  Display the measured distance by drawing lines on the map.
Metadata.json is not changed for measure, was it already correct?

2023-09-12 16:29 UTC, Jade-JadeH commented
Routing sample one I think the angle could be more top-down like the Unity one. 

Third person one---love it!

2023-09-12 17:58 UTC, avr757 commented on sample_project/Content/SampleViewer/Samples/Measure/readme.md
>  Display the measured distance by drawing lines on the map.
Yes, the image name is already matching 
![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/05d1a4e4-82c4-4c58-b4ed-71efc8c28ef7)

2023-09-12 17:59 UTC, avr757 commented
> Routing sample one I think the angle could be more top-down like the Unity one.

How about this one?


![Routing](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/85736034-7fda-4a78-8e90-189dfc4b6893)

2023-09-12 22:49 UTC, Jade-JadeH commented
I think the Unity one's angle looks better, I think it's better to not have a birdview so that it looks completely 2D.

2023-09-13 18:49 UTC, avr757 commented
> I think the Unity one's angle looks better, I think it's better to not have a birdview so that it looks completely 2D.

How about this angle?

![Routing](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/106696949/959dce05-49fa-4161-bf47-c9a6fcc4494c)

2023-09-13 20:26 UTC, Jade-JadeH commented
Thanks for keep working on it.

2023-09-13 20:26 UTC, Jade-JadeH approved these changes

2023-09-14 17:11 UTC, ZackAllen approved these changes

2023-09-14 17:15 UTC, merged