Mas12517/stream layer
Esri/arcgis-maps-sdk-unreal-engine-samples pull request #55
Opened 2023-10-16 20:03 UTC by mmgaw113

**Sample**

Stream Layer Sample

**Summary**

Stream Layer sample for Unreal Engine (not including UI)
To be merged into feature branch and then work on UI to begin after

**Tests**

Windows

**ArcGIS Maps SDK Version**

UE 5.0 w/ Maps SDK 1.3

2023-11-08 05:56 UTC, ZackAllen requested changes
Not seeing any airplanes show up when running the sample. Am I missing a step for seeing data come in from the stream layer?

2023-11-08 05:56 UTC, ZackAllen commented on sample_project/Source/sample_project/3DAttribute/APIMapCreator.cpp
> +// Copyright 2023 Esri.
These changes should not be present in this PR. Needs to be rebased.

2023-11-08 05:56 UTC, ZackAllen commented on sample_project/Source/sample_project/Stream Layer/DeadReckoning.cpp
> +// Fill out your copyright notice in the Description page of Project Settings.
Needs Esri copyright.

2023-11-08 05:56 UTC, ZackAllen commented on sample_project/Source/sample_project/Stream Layer/PlaneController.cpp
> +	auto metersPerSec = cGroundSpeedKnots * 0.51444444444;
Why 0.5144444?

2023-11-08 05:56 UTC, ZackAllen commented on sample_project/Source/sample_project/Stream Layer/StreamLayerQuery.cpp
> +
Unnecessary empty line. Can you run a formatter?

2023-11-08 05:56 UTC, ZackAllen commented on sample_project/Source/sample_project/Stream Layer/StreamLayerQuery.cpp
> +	WebSocket = FWebSocketsModule::Get().CreateWebSocket("wss://geoeventsample1.esri.com:6143/arcgis/ws/services/FAAStream/StreamServer/subscribe");
This string should definitely be a variable.

2023-11-08 05:56 UTC, ZackAllen commented on sample_project/Source/sample_project/Stream Layer/StreamLayerQuery.cpp
> +			Plane->PredictPoint(GetWorld()->GetDeltaSeconds() * 1000);
Why 1000? Could use a comment.

2023-11-08 05:56 UTC, ZackAllen commented on sample_project/Source/sample_project/Stream Layer/StreamLayerQuery.cpp
> +			UArcGISSpatialReference::CreateArcGISSpatialReference(4326)));
We should mention that this is WGS 84. Useful knowledge for those new to GIS.

2023-11-08 15:37 UTC, mmgaw113 commented on sample_project/Source/sample_project/3DAttribute/APIMapCreator.cpp
> +// Copyright 2023 Esri.
Merging into feature branch and feature branch was not up to date with main.

2023-11-08 15:38 UTC, mmgaw113 commented on sample_project/Source/sample_project/Stream Layer/PlaneController.cpp
> +	auto metersPerSec = cGroundSpeedKnots * 0.51444444444;
This is more or less copy and paste from the Unity Stream Layer Sample which Matt did. Any magic numbers present are from Matt and I have no idea what they actually mean.

2023-11-08 15:39 UTC, mmgaw113 commented on sample_project/Source/sample_project/Stream Layer/StreamLayerQuery.cpp
> +	WebSocket = FWebSocketsModule::Get().CreateWebSocket("wss://geoeventsample1.esri.com:6143/arcgis/ws/services/FAAStream/StreamServer/subscribe");
Not sure I agree. Since we don't have it setup to be able to be used with any stream layer (like how feature layer is setup) I don't think it needs to be a string at the moment. If we change it to be user configurable then it definitely needs to be a string.

2023-11-08 15:39 UTC, mmgaw113 commented on sample_project/Source/sample_project/Stream Layer/StreamLayerQuery.cpp
> +			Plane->PredictPoint(GetWorld()->GetDeltaSeconds() * 1000);
This is more or less copy and paste from the Unity Stream Layer Sample which Matt did. Any magic numbers present are from Matt and I have no idea what they actually mean.

2023-11-08 15:46 UTC, mmgaw113 commented
> Not seeing any airplanes show up when running the sample. Am I missing a step for seeing data come in from the stream layer?

Yeah I just checked and it's down again. I'm not sure what to do at this point. It is never going to get merged at this rate.

2023-11-08 17:25 UTC, ZackAllen commented on sample_project/Source/sample_project/Stream Layer/PlaneController.cpp
> +	auto metersPerSec = cGroundSpeedKnots * 0.51444444444;
If we don't know what it means, it shouldn't be in a sample used as public reference.

2023-11-21 21:50 UTC, avr757 approved these changes
I do see a number of planes get spawned in the Outliner window, and I checked most of these planes and they seem to be updating their positions in terms of Long and Lat. I assume more work w/ the camera and UI will be next once this is merged into the feature branch?

2023-11-21 22:03 UTC, mmgaw113 commented
> I do see a number of planes get spawned in the Outliner window, and I checked most of these planes and they seem to be updating their positions in terms of Long and Lat. I assume more work w/ the camera and UI will be next once this is merged into the feature branch?

Yes, moving the camera behind the plane will come with the UI.

2023-11-21 22:21 UTC, arash-sh commented on sample_project/Source/sample_project/Stream Layer/PlaneController.cpp
> +	mesh->SetupAttachment(RootComponent);
```suggestion
	RootComponent = mesh;
```

2023-11-21 22:22 UTC, arash-sh commented on sample_project/Source/sample_project/Stream Layer/PlaneController.cpp
> +	mesh->SetupAttachment(RootComponent);
This should take care of one set of warnings

2023-11-21 22:25 UTC, arash-sh commented on sample_project/Source/sample_project/Stream Layer/StreamLayerQuery.cpp
> +		if (auto Plane = FindObject<APlaneController>(ANY_PACKAGE, *name, true))
I think this line causes another set of warnings. Why not keep an array of pointers instead of searching at each iteration?

2023-11-21 22:30 UTC, mmgaw113 commented on sample_project/Source/sample_project/Stream Layer/StreamLayerQuery.cpp
> +		if (auto Plane = FindObject<APlaneController>(ANY_PACKAGE, *name, true))
I'm not seeing any warnings or errors in the console? 

The one you sent me earlier: `LogActor: Warning: PlaneController /Game/SampleViewer/UEDPIE_0_SampleViewerLevel.SampleViewerLevel:PersistentLevel.PlaneController_0 has natively added scene component(s), but none of them were set as the actor's RootComponent - picking one arbitrarily`

is fixed with the suggestion you made above.

2023-11-21 22:33 UTC, arash-sh commented
A few suggestions (some of which can be combined with future UI work)

- Add Esri copyright to all .cpp and .h
- Build lighting in the scene
- Rotate the planes to align with travel direction
- (optional) move the planes smoothly between points instead of jumps
- Once UI is working, remove the OnScreenDebugMessage and show a message or icon in the UI

2023-11-21 22:39 UTC, arash-sh commented on sample_project/Source/sample_project/Stream Layer/StreamLayerQuery.cpp
> +		if (auto Plane = FindObject<APlaneController>(ANY_PACKAGE, *name, true))
I was seeing warnings about ambiguous search path, but I can't reproduce them at the moment.

2023-11-21 23:16 UTC, merged